services:
  api:
    image: finance-api
    ports:
      - "8080:8080"
    environment:
      APP_PROFILE: dev
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres